apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: builds.config.openshift.io
spec:
  group: config.openshift.io
  version: v1
  scope: Cluster
  names:
    kind: Build
    singular: build
    plural: builds
    listKind: BuildList
  