apiVersion: config.openshift.io/v1
kind: CRIOCredentialProviderConfig
metadata:
  name: cluster
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
    release.openshift.io/feature-gate: "CRIOCredentialProviderConfig"
spec: {}
